# Generated by Django 5.1.2 on 2024-11-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
