### GET all submissions
GET http://localhost:8000/api/submissions

### GET all comments
GET http://localhost:8000/api/comments

### GET newest submissions
GET http://localhost:8000/api/submissions?sort=newest

### GET submission details by ID
GET http://localhost:8000/api/submissions/2

### Crear una nueva submission
POST http://localhost:8000/api/submissions
Content-Type: application/json
Authorization: Token 17e56252c5a6a3c2b5c58d398b69c9360bef4122

{
    "title": "API test",
    "url": "http://localhost:8000/swagger/"
}

### Get threads
GET http://localhost:8000/api/threads
Authorization: Token 17e56252c5a6a3c2b5c58d398b69c9360bef4122

### Get asks
GET http://localhost:8000/api/asks

### Get submissions by domain
GET http://localhost:8000/api/submissions?from=example.com

### Get user's profile
GET http://localhost:8000/api/users/3/profile

### Get user's submissions
GET http://localhost:8000/api/users/4/submissions